name: Release Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Package Extension (.vsix)
        run: npx @vscode/vsce package

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: "*.vsix"
          token: ${{ secrets.GITHUB_TOKEN }}
